export enum ActionTypes {
    SLIDER_UPLOAD_REQUEST = 'SLIDER_UPLOAD_REQUEST',
    SLIDER_UPLOAD_SUCCESS = 'SLIDER_UPLOAD_SUCCESS',
    SLIDER_UPLOAD_FAIL = 'SLIDER_UPLOAD_FAIL',
    SLIDER_RESET = 'SLIDER_RESET',
  }
  