export enum ActionTypes {
    FOOTER_UPLOAD_REQUEST = 'FOOTER_UPLOAD_REQUEST',
    FOOTER_UPLOAD_SUCCESS = 'FOOTER_UPLOAD_SUCCESS',
    FOOTER_UPLOAD_FAIL = 'FOOTER_UPLOAD_FAIL',

    FOOTER_FETCH_REQUEST = 'FOOTER_FETCH_REQUEST',
    FOOTER_FETCH_SUCCESS = 'FOOTER_FETCH_SUCCESS',
    FOOTER_FETCH_FAIL = 'FOOTER_FETCH_FAIL',

    FOOTER_DELETE_REQUEST = 'FOOTER_DELETE_REQUEST',
    FOOTER_DELETE_SUCCESS = 'FOOTER_DELETE_SUCCESS',
    FOOTER_DELETE_FAIL = 'FOOTER_DELETE_FAIL',

    FOOTER_RESET = 'FOOTER_RESET',
  }
  