export enum ActionTypes {
    FOOTER_UPLOAD_REQUEST = 'FOOTER_UPLOAD_REQUEST',
    FOOTER_UPLOAD_SUCCESS = 'FOOTER_UPLOAD_SUCCESS',
    FOOTER_UPLOAD_FAIL = 'FOOTER_UPLOAD_FAIL',

    FOOTER_FETCH_REQUEST = 'FOOTER_FETCH_REQUEST',
    FOOTER_FETCH_SUCCESS = 'FOOTER_FETCH_SUCCESS',
    FOOTER_FETCH_FAIL = 'FOOTER_FETCH_FAIL',

    FOOTER_DELETE_REQUEST = 'FOOTER_DELETE_REQUEST',
    FOOTER_DELETE_SUCCESS = 'FOOTER_DELETE_SUCCESS',
    FOOTER_DELETE_FAIL = 'FOOTER_DELETE_FAIL',

    FOOTER_RESET = 'FOOTER_RESET',

    SERVICES_UPLOAD_REQUEST = 'SERVICES_UPLOAD_REQUEST',
    SERVICES_UPLOAD_SUCCESS = 'SERVICES_UPLOAD_SUCCESS',  

    SERVICES_UPLOAD_FAIL = 'SERVICES_UPLOAD_FAIL',
    SERVICES_FETCH_REQUEST = 'SERVICES_FETCH_REQUEST',
    SERVICES_FETCH_SUCCESS = 'SERVICES_FETCH_SUCCESS',
    SERVICES_FETCH_FAIL = 'SERVICES_FETCH_FAIL',
    SERVICES_DELETE_REQUEST = 'SERVICES_DELETE_REQUEST',
    SERVICES_DELETE_SUCCESS = 'SERVICES_DELETE_SUCCESS',
    SERVICES_DELETE_FAIL = 'SERVICES_DELETE_FAIL',
    SERVICES_RESET = 'SERVICES_RESET',
    SERVICES_UPDATE_REQUEST = 'SERVICES_UPDATE_REQUEST',
    SERVICES_UPDATE_SUCCESS = 'SERVICES_UPDATE_SUCCESS',    
  
  }
  